apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: database-composition
spec:
  compositeTypeRef:
    apiVersion: rcarlsondevops.org/v1alpha1
    kind: PostgresDatabase
  mode: Pipeline
  pipeline:
    - step: create-a-namespace
      functionRef:
        name: go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            apiVersion: v1
            kind: Namespace
            metadata:
              name: "{{ .observed.composite.resource.metadata.name }}-db"
              labels:
                team: "{{ .observed.composite.resource.spec.team }}"
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: namespace
    - step: create-a-postgres-database
      functionRef:
        name: go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            apiVersion: postgresql.cnpg.io/v1
            kind: Cluster
            metadata:
              name: postgres-db
              namespace: "{{ .observed.composite.resource.metadata.name }}-db"
              labels:
                team: "{{ .observed.composite.resource.spec.team }}"
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: postgres-instance
            spec:
              instances: {{ .observed.composite.resource.spec.instances }}
              storage:
                {{- $sizeDict := dict "small" "1Gi" "medium" "2Gi" "large" "3Gi" }}
                size: "{{ get $sizeDict .observed.composite.resource.spec.size }}"
    - step: create-cluster-rolebinding
      functionRef:
        name: go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        source: Inline
        inline:
          template: |
            apiVersion: rbac.authorization.k8s.io/v1
            kind: RoleBinding
            metadata:
              namespace: "{{ .observed.composite.resource.metadata.name }}-db"
              name: "{{ .observed.composite.resource.metadata.name }}-rolebinding-db"
              labels:
                team: "{{ .observed.composite.resource.spec.team }}"
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: rolebinding
                gotemplating.fn.crossplane.io/ready: "True"
            subjects:
              - kind: Group
                name: "{{ .observed.composite.resource.spec.team }}"
            roleRef:
              kind: ClusterRole
              name: edit
              apiGroup: rbac.authorization.k8s.io
    - step: auto-detect-ready-composed-resources
      functionRef:
        name: auto-ready
    - step: sequence-creation
      functionRef:
        name: function-sequencer
      input:
        apiVersion: sequencer.fn.crossplane.io/v1beta1
        kind: Input
        rules:
          - sequence:
              - namespace
              - postgres-instance
              - rolebinding