apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cnpg:aggregate-to-crossplane
  labels:
    rbac.crossplane.io/aggregate-to-crossplane: "true"
rules:
- apiGroups: ["postgresql.cnpg.io"]
  resources: ["clusters", "clusters/status"]
  verbs:
  - "*"
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["*"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["rolebindings", "rolebindings/status"]
  verbs: ["create", "update", "delete", "patch", "get", "list", "watch"]
- apiGroups: ["rbac.authorization.k8s.io"]
  resources: ["clusterrolebindings", "clusterrolebindings/status"]
  verbs: ["bind"]

