apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-credentials
  namespace: form-test
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: db-credentials
    creationPolicy: Owner
  data:
    - secretKey: dbname
      remoteRef:
        key: tenants/form-test/db
        property: dbname
    - secretKey: username
      remoteRef:
        key: tenants/form-test/db
        property: username
    - secretKey: password
      remoteRef:
        key: tenants/form-test/db
        property: password
