apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: db-credentials
  namespace: form-test-db
spec:
  secretStoreRefs:
    - name: vault-backend
      kind: ClusterSecretStore
  selector:
    secret:
      name: postgres-db-app
  data:
    - match:
        secretKey: password
        remoteRef:
          remoteKey: tenants/form-test/db
          property: password
    - match:
        secretKey: username
        remoteRef:
          remoteKey: tenants/form-test/db
          property: username
    - match:
        secretKey: dbname
        remoteRef:
          remoteKey: tenants/form-test/db
          property: dbname