name: Deploy go-app-template and database
on:
  workflow_dispatch:
    inputs:
      team:
        description: 'The team name which will be used to name all resources deployed'
        required: true
        type: string
      instances:
        description: 'The number of database instances to deploy'
        required: true
        type: choice
        options:
          - '1'
          - '2'
          - '3'
      size:
        description: 'The size of the database to deploy'
        required: true
        type: choice
        options:
          - small
          - medium
          - large
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Validate inputs
        run: |
          if [ "${{ inputs.team }}" -gt 60 ]; then
            echo "Error: Team name must be 60 characters or less."
            exit 1
          fi
          if [[ ! "${{ inputs.team }}" =~ ^[a-z0-9]([a-z0-9-]{0,58}[a-z0-9])?$ ]]; then
            echo "Error: Team name must be alphanumeric and can include hyphens, but cannot start or end with a hyphen."
            exit 1
          fi
          if [[ ! "${{ inputs.instances }}" =~ ^[1-3]$ ]]; then
            echo "Error: Instances must be 1, 2, or 3."
            exit 1
          fi
          if [[ ! "${{ inputs.size }}" =~ ^(small|medium|large)$ ]]; then
            echo "Error: Size must be small, medium, or large."
            exit 1
          fi
  deploy_new_repo:
    runs-on: ubuntu-latest
    needs: validate
    env:
      GH_TOKEN: ${{ secrets.REPO_CREATOR_PAT }}
      TEAM: ${{ inputs.team }}
    steps:
      - name: deploy
        run: |
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-Github-Api-Version: 2022-11-28" \
            "/repos/rcarlson-devops/go-app-template/generate" \
            -f name="${TEAM}" \
            -F private=false
  populate_tenants:
    runs-on: ubuntu-latest
    needs: deploy_new_repo
    env:
      TEAM: ${{ inputs.team }}
      INSTANCES: ${{ inputs.instances }}
      SIZE: ${{ inputs.size }}
    steps:
      - name: Wait for new repo to push docker image
        uses: replayio/action-wait-for-ghcr-image@latest
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          github-username: ${{ secrets.GITHUB_ACTOR }}
          image-name: "ghcr.io/rcarlson-devops/${{ inputs.team }}:latest" 
      - name: Checkout repository
        uses: actions/checkout@v7
      - name: Copy application.yaml.tmpl to tenants
        run: "mkdir \"./argocd/tenants/${TEAM}\" \ncp ./self-service/templates/application.yaml.tmpl \"./argocd/tenants/${TEAM}/application.yaml\"\n"
      - name: Copy database.yaml.tmpl to tenants
        run: cp ./self-service/templates/database.yaml.tmpl "./argocd/tenants/${TEAM}/database.yaml"
      - name: Replace placeholders in application.yaml
        run: |
          yq -i '(.metadata.name) = strenv(TEAM)' "./argocd/tenants/${TEAM}/application.yaml"
          yq -i '(.spec.sources[1].repoURL) = "https://github.com/rcarlson-devops/" + strenv(TEAM) + ".git"' "./argocd/tenants/${TEAM}/application.yaml"
          yq -i '(.spec.destination.namespace) = strenv(TEAM)' "./argocd/tenants/${TEAM}/application.yaml"
      - name: Replace placeholders in database.yaml
        run: |
          yq -i '(.metadata.name) = strenv(TEAM)' "./argocd/tenants/${TEAM}/database.yaml"
          yq -i '(.spec.team) = strenv(TEAM)' "./argocd/tenants/${TEAM}/database.yaml"
          yq -i '(.spec.instances) = (strenv(INSTANCES) | tonumber)' "./argocd/tenants/${TEAM}/database.yaml"
          yq -i '(.spec.size) = strenv(SIZE)' "./argocd/tenants/${TEAM}/database.yaml"
      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add "./argocd/tenants/${TEAM}/application.yaml" "./argocd/tenants/${TEAM}/database.yaml"
          git commit -m "Add application and database manifests for team ${TEAM}"
          git push origin HEAD:main
