# helm upgrade --install hello-world ./charts/hello-world \
#   -f ./environments/dev/values-dev.yaml \
#   --namespace hello-world-dev --create-namespace

replicaCount: 1
image:
  tag: sha-8c5750b
environment: dev
